### ISSUE TITLE
Some malli functions don't work in CLJS release mode

### ISSUE THREAD

**Issue by khmelevskii** [metosin/malli#603]
Everything works great in development mode, but in production mode I have an errors with such function like `mu/merge` or `m/walk`.

My shadow-cljs config
```
{:deps true
 :builds
 {:storybook {:target           :npm-module
              :output-dir       "public/js/stories"
              :ns-regexp        ".stories$"
              :compiler-options {:infer-externs true}}}}
```

I'm not sure that error in console can be useful
```
TypeError: Cannot read properties of undefined (reading 'prototype')
    at Object.<anonymous> (http://localhost:9080/main.6b9fd58f.iframe.bundle.js:1:685144)
    at Object../public/js/stories/malli.generator.js (http://localhost:9080/main.6b9fd58f.iframe.bundle.js:1:698104)
```

Please let me know if I need to prepare minimalistic repo with this problem

**Comment by opqdonut** [comment]
This is interesting because we do run the CLJS test suite with advanced compilation. Repro welcome!

**Comment by opqdonut** [comment]
Please reopen if you still see this problem!
