### ISSUE TITLE
Malli cljs ExceptionInfo is not enough to figure out where the exception occurred

### ISSUE THREAD

**Issue by philoskim** [metosin/malli#972]
* malli version: 0.13.0

The following is the problematic example.

```
;; malli_test/main.cljs
(ns malli-test.main
  (:require [malli.core :as m]
            [malli.instrument :as mi]))

(m/=> power [:=> [:cat :int] [:int {:max 6}]])
(defn power [x] (* x x))

(mi/instrument!)

(power "6")

cljs$core$ExceptionInfo {message: ':malli.core/invalid-input', data: {…}, cause: null, name: 'Error', description: undefined, …}
cause : null
columnNumber : undefined
data : cljs.core/PersistentArrayMap [count: 3]
description : undefined
fileName : undefined
lineNumber : undefined
message : ":malli.core/invalid-input"
name : "Error"
number : undefined
stack : "Error: :malli.core/invalid-input\n    at new cljs$core$ExceptionInfo (file:///js/cljs-runtime/cljs.core.js:37369:10)\n    at Function.eval [as cljs$core$IFn$_invoke$arity$3] (file:///js/cljs-runtime/cljs.core.js:37430:9)\n    at Function.eval [as cljs$core$IFn$_invoke$arity$2] (file:///js/cljs-runtime/cljs.core.js:37426:26)\n    at Function.eval [as cljs$core$IFn$_invoke$arity$2] (file:///js/cljs-runtime/malli.core.js:1253:26)\n    at Function.eval [as cljs$core$IFn$_invoke$arity$2] (file:///js/cljs-runtime/malli.core.js:1280:29)\n    at Object.G__28317__delegate (file:///js/cljs-runtime/malli.core.js:12285:48)\n    at Object.G__28317 (file:///js/cljs-runtime/malli.core.js:12310:27)\n    at eval (file:///js/cljs-runtime/malli_test.main.js:8:17)\n    at eval (<anonymous>)\n    at goog.globalEval (file:///Users/philos/work/malli-test/resources/public/js/main.js:434:11)"
```

The above ExceptionInfo doesn't show any fileName, lineNumber and columnNumber.

How can I figure out where the exception occurred?

**Comment by dvingo** [comment]
For clojure you can use https://clojuredocs.org/clojure.core/*e

For cljs it looks like you don't have cljs devtools installed, you can find instructions on getting setup here:

https://github.com/metosin/malli/blob/master/docs/clojurescript-function-instrumentation.md

with details on how to find the source of your error in your codebase.

**Comment by ikitommi** [comment]
How does this look with the new development mode?
